/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

#include <math.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "nrscope/hdr/sensing/nr_ue_sensing.h"
#include "nrscope/hdr/sensing/nr_ue_map.h"
#include "nrscope/hdr/sensing/nr_ue_sensing_align.h"

int nr_sensing_tdd_period_slots = 10;

bool nr_ue_sensing_extract_lattice(int n_sc,
                                   const cf_t H_row[n_sc],
                                   const bool valid_row[n_sc],
                                   int max_out,
                                   cf_t out[max_out],
                                   pilot_lattice_t *lattice)
{
  int n = 0;
  int k_first = -1;
  int k_prev = -1;
  int k_step = 0;

  /* First pass: identify the lattice. Only its step and offset are read here, the
  values are placed in a second pass once the step is known. */
  for (int k = 0; k < n_sc; k++) {
    if (!valid_row[k])
      continue;
    if (k_first < 0) {
      k_first = k;
    } else {
      const int step = k - k_prev;
      if (k_step == 0)
        k_step = step;
      else if (step != k_step) {
        // an error would happen
        LOG_E(NR_PHY, "sensing: non-uniform pilot lattice (step %d then %d at k=%d)\n", k_step, step, k);
        return false;
      }
    }
    n++;
    k_prev = k;
  }

  if (n < 2)
    return false;

  /* The lattice is every subcarrier of the carrier congruent to k_first mod k_step,
  so it stays put when the scheduler moves the grant: only the number of its
  positions that carry a measurement changes. Each pilot goes to its own position
  and the rest stay zero. */
  const int offset = k_first % k_step;
  const int n_lattice = (n_sc - offset + k_step - 1) / k_step;
  if (n_lattice > max_out) {
    LOG_E(NR_PHY, "sensing: lattice of %d positions does not fit %d entries\n", n_lattice, max_out);
    return false;
  }
  memset(out, 0, n_lattice * sizeof(*out));
  for (int k = k_first; k <= k_prev; k += k_step)
    out[(k - offset) / k_step] = H_row[k];

  lattice->n = n;
  lattice->n_lattice = n_lattice;
  lattice->k_first = k_first;
  lattice->k_step = k_step;
  return true;
}

bool nr_ue_sensing_hann_coeffs(int L, float *w)
{
  if (L < 8)
    return false;

  /* w[i] = 0.5 * (1 - cos(2*pi*i/(L-1))), symmetric form, generated by the Chebyshev
  recurrence cos(i*th) = 2*cos(th)*cos((i-1)*th) - cos((i-2)*th) rather than by calling
  cos() L times per symbol per antenna. In double the recurrence drifts by ~1e-12 over
  the 1638 positions of a full band grant, far below the Q15 quantisation applied by
  nr_ue_sensing_apply_hann(). */
  const double th = 2.0 * M_PI / (L - 1);
  const double two_cos_th = 2.0 * cos(th);
  double c_prev2 = 1.0; // cos(0)
  double c_prev1 = cos(th);

  for (int i = 0; i < L; i++) {
    double c;
    if (i == 0)
      c = c_prev2;
    else if (i == 1)
      c = c_prev1;
    else {
      c = two_cos_th * c_prev1 - c_prev2;
      c_prev2 = c_prev1;
      c_prev1 = c;
    }
    w[i] = (float)(0.5 * (1.0 - c));
  }
  return true;
}

void nr_ue_sensing_apply_hann(const pilot_lattice_t *lattice, cf_t *out)
{
  const int L = lattice->n;
  float w[NR_SENSING_MAX_IDFT];

  AssertFatal(L <= NR_SENSING_MAX_IDFT, "sensing: %d pilots do not fit a Hann window\n", L);
  if (!nr_ue_sensing_hann_coeffs(L, w))
    return; // degenerate lattice, leave it rectangular rather than mute it

  // first lattice position carrying a measurement; the span is contiguous because
  // nr_ue_sensing_extract_lattice() rejects anything that is not a uniform lattice
  const int a = (lattice->k_first - (lattice->k_first % lattice->k_step)) / lattice->k_step;

  /* In Q15 this had to round each coefficient to an integer and shift the
  product back down. In complex float the taper is just a scale, so the
  quantisation of the window itself is gone; the coherent gain of 0.5 that the
  comment above describes is unchanged, since it is a property of Hann and not
  of the arithmetic. */
  for (int i = 0; i < L; i++) {
    out[a + i] *= w[i];
  }
}

/* splitmix64 finaliser, used to draw what the random drop leaves out.

The input is the absolute slot index, which advances by one per slot and is
far from random, so it has to be mixed before any bit of it is usable.

Deriving the draws from those values rather than from a stateful generator matters
for two reasons: every Rx antenna then reaches the same decision, so their histories
stay in step and can still be combined, and a recorded capture replays identically. */
static uint64_t nr_ue_sensing_mix(uint64_t x)
{
  x += 0x9E3779B97F4A7C15ULL;
  x = (x ^ (x >> 30)) * 0xBF58476D1CE4E5B9ULL;
  x = (x ^ (x >> 27)) * 0x94D049BB133111EBULL;
  return x ^ (x >> 31);
}

/* GRANT EMULATION, for simulation only. Rebuild after changing it.

Over ZMQ with a single UE, the gNB schedules nearly the whole band from the same RB in
every slot, so the grant size and grant position effects of a real network never show up
in the map. A non-zero value makes the sensing path see a different grant in every slot, by
keeping only a sub-interval of the pilots the UE actually measured:

  0  off. The default, and the only value for a real deployment.
  1  random: a new grant per slot. NR_SENSING_EMUL_FULL_PERCENT % of the slots get the full
     carrier, the others a size uniform in [NR_SENSING_EMUL_MIN_RB, carrier] RBs at a
     uniform start.
  2  replay: the per-slot grants of a snapshot dump written by
     nr_ue_sensing_dump_snapshots(), for instance from an outdoor capture, read once from
     NR_SENSING_EMUL_TRACE and cycled through.

Only the sensing path is affected: decoding still uses the grant the gNB sent. Emulation can
only shrink what was measured, so the gNB must schedule a wide grant (full buffer traffic).
The draw depends on the slot index alone, so every antenna and layer of one slot sees the
same grant, as a real PDSCH would, and a recorded capture replays identically. What is not
emulated: a precoder that changes with the grant, and in replay the idle gaps between the
trace's slots (consecutive slots here take consecutive trace entries). */
#define NR_SENSING_EMULATE_GRANTS 0
/// smallest random grant, in RBs (mode 1)
#define NR_SENSING_EMUL_MIN_RB 25
/// share of slots given the full carrier, in percent (mode 1)
#define NR_SENSING_EMUL_FULL_PERCENT 30
/// snapshot dump to replay (mode 2)
#define NR_SENSING_EMUL_TRACE "/tmp/grant_trace.snap.csv"
/// most slots kept from the trace (mode 2)
#define NR_SENSING_EMUL_MAX_SLOTS 65536

#if NR_SENSING_EMULATE_GRANTS != 0

#if NR_SENSING_EMULATE_GRANTS == 2
typedef struct {
  int k_step;
  /// lattice index of the first pilot, a_m
  int a;
  /// pilots in the grant, n_m
  int n;
} nr_sensing_emul_grant_t;

static nr_sensing_emul_grant_t *emul_trace;
static int emul_trace_len;
#endif

static pthread_once_t emul_once = PTHREAD_ONCE_INIT;

/* Announce the emulation once, so a build with it left on cannot go unnoticed, and in replay
mode load the trace. The dump has one row per reference symbol and every symbol of one slot
carries the same PDSCH grant, so only the first row of each slot is kept. */
static void nr_ue_sensing_emul_init(void)
{
#if NR_SENSING_EMULATE_GRANTS == 1
  LOG_W(NR_PHY,
        "sensing: GRANT EMULATION ACTIVE (random, %d %% full band, else >= %d RB). Simulation only.\n",
        NR_SENSING_EMUL_FULL_PERCENT,
        NR_SENSING_EMUL_MIN_RB);
#else
  FILE *f = fopen(NR_SENSING_EMUL_TRACE, "r");
  if (f == NULL) {
    LOG_E(NR_PHY, "sensing: grant emulation cannot open %s, emulation stays off\n", NR_SENSING_EMUL_TRACE);
    return;
  }
  emul_trace = malloc_or_fail(NR_SENSING_EMUL_MAX_SLOTS * sizeof(*emul_trace));

  char *line = NULL;
  size_t cap = 0;
  long long last_slot = -1;
  while (getline(&line, &cap, f) > 0 && emul_trace_len < NR_SENSING_EMUL_MAX_SLOTS) {
    unsigned long t_sample;
    int k_step, k_first, n_pilots, scs_hz;
    double fs_hz;
    // snap,t_sample,t_rel_s,k_step,k_first,n_pilots,idft_size,n_bins,scs_hz,fs_hz,...
    if (sscanf(line, "%*d,%lu,%*f,%d,%d,%d,%*d,%*d,%d,%lf", &t_sample, &k_step, &k_first, &n_pilots, &scs_hz, &fs_hz) != 6
        || k_step <= 0 || scs_hz <= 0)
      continue; // the header, or a line this parser does not know
    const double slot_len = fs_hz / (1000.0 * scs_hz / 15000.0);
    const long long slot = (long long)(t_sample / slot_len);
    if (slot == last_slot)
      continue;
    last_slot = slot;
    emul_trace[emul_trace_len++] =
        (nr_sensing_emul_grant_t){.k_step = k_step, .a = (k_first - k_first % k_step) / k_step, .n = n_pilots};
  }
  free(line);
  fclose(f);

  if (emul_trace_len == 0)
    LOG_E(NR_PHY, "sensing: grant emulation found no snapshot in %s, emulation stays off\n", NR_SENSING_EMUL_TRACE);
  else
    LOG_W(NR_PHY,
          "sensing: GRANT EMULATION ACTIVE (replay of %d slots from %s). Simulation only.\n",
          emul_trace_len,
          NR_SENSING_EMUL_TRACE);
#endif
}

/* The emulated grant of a slot, as (a, n): lattice index of its first pilot and pilot count.
False when nothing applies to this lattice, which then keeps what was measured. */
static bool nr_ue_sensing_emulated_grant(uint64_t slot_abs, int n_sc, int k_step, int *a, int *n)
{
  pthread_once(&emul_once, nr_ue_sensing_emul_init);
#if NR_SENSING_EMULATE_GRANTS == 1
  /* A grant is whole RBs, and an RB holds 12 / k_step lattice positions: k_first is
  12 * RB + delta with delta < k_step, so the lattice index of an RB start is RB * 12 / k_step. */
  if (k_step <= 0 || 12 % k_step != 0)
    return false;
  const int per_rb = 12 / k_step;
  const int n_rb = n_sc / 12;
  const int min_rb = NR_SENSING_EMUL_MIN_RB < n_rb ? NR_SENSING_EMUL_MIN_RB : n_rb;
  const uint64_t h = nr_ue_sensing_mix(slot_abs ^ 0x6772616E74ULL);
  const int nof_rb = (int)(h % 100) < NR_SENSING_EMUL_FULL_PERCENT
                         ? n_rb
                         : min_rb + (int)(nr_ue_sensing_mix(h) % (uint64_t)(n_rb - min_rb + 1));
  const int start_rb = (int)(nr_ue_sensing_mix(h + 1) % (uint64_t)(n_rb - nof_rb + 1));
  *a = start_rb * per_rb;
  *n = nof_rb * per_rb;
  return true;
#else
  (void)n_sc;
  if (emul_trace_len == 0)
    return false;
  const nr_sensing_emul_grant_t *g = &emul_trace[slot_abs % (uint64_t)emul_trace_len];
  if (g->k_step != k_step)
    return false;
  *a = g->a;
  *n = g->n;
  return true;
#endif
}

/* Keep only the lattice positions inside [a, a + n): the rest of the measured span is zeroed
and the lattice now describes the intersection. False when fewer than 2 pilots are left. */
static bool nr_ue_sensing_restrict_lattice(pilot_lattice_t *lat, cf_t *pilots, int a, int n)
{
  const int offset = lat->k_first % lat->k_step;
  const int a_meas = (lat->k_first - offset) / lat->k_step;
  const int lo = a > a_meas ? a : a_meas;
  const int hi = (a + n) < (a_meas + lat->n) ? (a + n) : (a_meas + lat->n);
  if (hi - lo < 2)
    return false;
  memset(&pilots[a_meas], 0, (lo - a_meas) * sizeof(*pilots));
  memset(&pilots[hi], 0, (a_meas + lat->n - hi) * sizeof(*pilots));
  lat->k_first = offset + lo * lat->k_step;
  lat->n = hi - lo;
  return true;
}

#endif

int nr_ue_sensing_slot_profile(int n_sym,
                               int n_sc,
                               const cf_t H_est_ant[n_sym][n_sc],
                               const bool H_valid[n_sym][n_sc],
                               const uint64_t t_sample[n_sym],
                               nr_sensing_history_t *hist,
                               nr_sensing_stream_t stream,
                               uint64_t slot_abs,
                               bool random_drop,
                               uint16_t skip_mask,
                               pilot_lattice_t *lattice,
                               uint16_t *used_mask)
{
  cf_t pilots[n_sc];
  pilot_lattice_t lat_ref = {0};
  bool have_ref = false;
  int idft_size = 0;
  *used_mask = 0;

  /* Random drop: whether this slot loses a symbol, and which. Drawn from the slot
  index, so every antenna and layer of the slot agrees, and among the symbols the
  caller offers (its DM-RS symbols) rather than the ones that end up accepted, so the
  draw does not depend on the estimates. -1 keeps them all. */
  int drop_m = -1;
  if (random_drop) {
    const uint64_t h = nr_ue_sensing_mix(slot_abs);
    int n_cand = 0;
    for (int m = 0; m < n_sym; m++)
      n_cand += !(skip_mask & (1 << m));
    if (n_cand > 0 && (h % NR_SENSING_DROP_ONE_IN) == 0) {
      int r = (int)((h >> 32) % (uint64_t)n_cand);
      for (int m = 0; m < n_sym && drop_m < 0; m++)
        if (!(skip_mask & (1 << m)) && r-- == 0)
          drop_m = m;
    }
  }

  /* One profile per symbol can reach 2*32767^2, so three of them overflow a
  uint32_t. Accumulate in 64 bits and divide back down at the end. */
  uint64_t accum[NR_SENSING_MAX_IDFT];
  int n_averaged = 0;

  for (int m = 0; m < n_sym; m++) {
    if (skip_mask & (1 << m))
      continue;
    pilot_lattice_t lat;
    if (!nr_ue_sensing_extract_lattice(n_sc, H_est_ant[m], H_valid[m], n_sc, pilots, &lat))
      continue;

    // A narrow grant is dropped rather than averaged in, or just taken into account.
    if (lat.n * NR_SENSING_MIN_BAND_DEN < lat.n_lattice * NR_SENSING_MIN_BAND_NUM) {
      //LOG_I(NR_PHY, "sensing: narrow lattice of %d pilots over %d positions is dropped\n", lat.n, lat.n_lattice);
      continue;
    }
#if NR_SENSING_EMULATE_GRANTS != 0
    /* Simulation only: this slot's emulated grant replaces what was measured, before anything
    reads the lattice, so the taper, the history and the map all see it. */
    {
      int a_emu, n_emu;
      if (nr_ue_sensing_emulated_grant(slot_abs, n_sc, lat.k_step, &a_emu, &n_emu)
          && !nr_ue_sensing_restrict_lattice(&lat, pilots, a_emu, n_emu))
        continue; // the emulated grant misses the measured span
    }
#endif

#if NR_SENSING_ALIGN
    /* Bring this symbol's static scene back onto
    the reference (FFT window moves, phase jumps) before anything reads the pilots. A
    symbol that does not match the reference is left out. */
    if (!nr_ue_sensing_align_symbol(t_sample[m], stream, &lat, pilots, NULL))
      continue;
#endif

    // if (lat.n < 50) {
    //   LOG_I(NR_PHY, "sensing: %d pilots\n", lat.n);
    //   continue;
    // }

    /* Sized from the pilot spacing so that every reference signal shares one delay
    axis; see NR_SENSING_DELAY_SPAN. The bound holds for any comb of a standard
    carrier, so a failure here means a lattice we do not model. */
    const int size = NR_SENSING_IDFT_SIZE(lat.k_step);
    if (size > NR_SENSING_MAX_IDFT || lat.n_lattice > size) {
      LOG_E(NR_PHY,
            "sensing: lattice of %d positions at k_step %d does not fit a %d point IDFT\n",
            lat.n_lattice,
            lat.k_step,
            size);
      return 0;
    }

    /* Symbols group by lattice, not by grant: k_step and the comb offset have to
    match, but the number of PRBs scheduled need not, because the lattice indexing
    in nr_ue_sensing_extract_lattice() puts every allocation on one delay axis. */
    if (!have_ref) {
      have_ref = true;
      lat_ref = lat;
      idft_size = size;
      memset(accum, 0, idft_size * sizeof(*accum));
    } else if (lat.k_step != lat_ref.k_step || (lat.k_first % lat.k_step) != (lat_ref.k_first % lat_ref.k_step)) {
      continue; // different reference signal, left for a later pass
    } else if (lat.n < lat_ref.n) {
      lat_ref.n = lat.n; // report the coarsest resolution that went into the average
    }

    /* Taper before transforming, or the rectangular edges of the grant put -13 dB
    sidelobes on every path in the profile. Applied here rather than inside
    nr_ue_sensing_delay_response() so the raw LS values stay untouched up to this
    point, and so both users of the response below get the same tapered version. */

    /* Measured: with this line removed, the TDD replica stripes at multiples of
    1/T_TDD reappear across the whole range axis. They are not a slow-time artefact
    that a slow-time fix could reach. A rectangular window leaves the direct path
    about -40 dB of leakage in a bin 100 m away, against about -99 dB under a Hann
    taper, and that leakage is what the scheduler modulates: its value carries both
    the kernel shape, which changes with the grant width, and a phase exp(j*2*pi*a*u/N)
    that at u = 40 bins turns a full cycle for every 51 lattice positions the grant
    start moves. One scheduler modulates every far bin the same way, so every range
    shows the same Doppler signature, which is why the artefact is a vertical stripe.
    Taper the window and the leakage is below the floor in every slot, leaving
    nothing to modulate.

    Normalising by the pilot count does not reach this: it is one scalar per
    snapshot, and a scalar cannot undo a change of kernel shape or a phase ramp. It
    corrects the height of a peak, which is a different part of the map. */
    nr_ue_sensing_apply_hann(&lat, pilots);

    /* The complex response is computed once and used twice: the history keeps it
    as one slow-time sample for the Doppler axis, while its magnitude accumulates
    into this slot's range profile. Squaring first would destroy the phase the
    Doppler needs, so the order matters. */
    __attribute__((aligned(32))) cf_t h_time[NR_SENSING_MAX_IDFT];
    nr_ue_sensing_delay_response(lat.n_lattice, pilots, idft_size, h_time);

    /* If we store the complex response, then we store the time of the symbol as well,
    so that the Doppler transform can be done later. The random drop leaves out at most
    one symbol of the slot. The range profile below still averages every symbol: it is
    built from magnitudes and does not care how the samples are spaced in time. */
    if (hist && m != drop_m) {
      nr_ue_sensing_history_push(hist, t_sample[m], stream, &lat, idft_size, h_time);
    }

    // each h_time[b] is a X[k] after the IDFT. The modulus squared |X[k]|^2
    // is the c16amp2(h_time[b]).
    // The idea is to accumulate the modulus squared of each h_time[b] into accum[b],
    // and then average it at the end to get one range profile with a variance that decreased by 1/M.
    // In fact, the range profile is not dependent on the symbol index. So we average over multiple
    // symbols to get a better estimate of the range profile.

    // not needed anymore.
    // for (int b = 0; b < idft_size; b++) {
    //   accum[b] += c16amp2(h_time[b]);
    // }

    *used_mask |= (1 << m);
    n_averaged++;
  }

  if (n_averaged == 0) return 0;

  *lattice = lat_ref;
  return idft_size;
}

uint64_t nr_ue_sensing_symbol_time(int hfn,
                                   int frame,
                                   int slot,
                                   int symbol,
                                   int symbols_per_slot,
                                   int numerology,
                                   uint32_t samples_per_frame,
                                   uint32_t slot_timestamp,
                                   int ofdm_symbol_size,
                                   int nb_prefix_samples,
                                   int nb_prefix_samples0)
{
  /* Same arithmetic as nr_slot_fep(): walk the symbols of the slot adding each
  cyclic prefix, because the first symbol of every half subframe uses the longer
  nb_prefix_samples0. The frame counter is extended with the hyper frame number so
  the timestamp keeps increasing past the 1024 frame wrap. */
  uint64_t t = (uint64_t)((unsigned)hfn * 1024u + (unsigned)frame) * samples_per_frame;
  t += slot_timestamp;
  const int abs_symbol = slot * symbols_per_slot + symbol;
  for (int i = slot * symbols_per_slot; i <= abs_symbol; i++)
    t += (i % (0x7 << numerology)) ? nb_prefix_samples : nb_prefix_samples0;
  t += (uint64_t)ofdm_symbol_size * symbol;
  return t;
}

// This function adds zero-padding for efficiently computing the profile.
// H_lattice holds one entry per lattice position, already zero where nothing was
// measured, so the padding here only extends the transform past the end of the
// carrier. A bigger idft_size than n_lattice gives a finer grid in the delay domain
// without changing the resolution, which is set by the occupied bandwidth alone.
void nr_ue_sensing_delay_response(int n_lattice, const cf_t H_lattice[n_lattice], int idft_size, cf_t time_out[idft_size])
{
  AssertFatal(n_lattice > 0 && n_lattice <= idft_size,
              "sensing: %d lattice positions do not fit an IDFT of size %d\n",
              n_lattice,
              idft_size);

  // padding the input with zeros
  __attribute__((aligned(32))) cf_t in[idft_size];
  memcpy(in, H_lattice, n_lattice * sizeof(cf_t));
  memset(&in[n_lattice], 0, (idft_size - n_lattice) * sizeof(cf_t));

  /* Compute IDFT into time_out. OAI looked the transform up by size from a
  static table and took int16 buffers; srsRAN needs a plan object, which
  nr_ue_sensing_idft() creates on first use and caches. A refusal here means the
  size is one the plan cache will not build, which leaves time_out untouched
  rather than filled with a slower transform on the receive path. */
  if (nr_ue_sensing_idft(idft_size, in, time_out) != 0) {
    memset(time_out, 0, idft_size * sizeof(cf_t));
  }
}

/* Distance between two bins of a profile that wraps at n_bins, so bin 0 and bin
n_bins-1 are neighbours rather than the furthest apart pair. */
static int nr_ue_sensing_bin_distance(int a, int b, int n_bins)
{
  const int d = abs(a - b);
  return (d > n_bins / 2) ? n_bins - d : d;
}
